version: '3'

services:
  pulsar:
    image: apachepulsar/pulsar:2.9.2
    ports:
      - "6650:6650"
      - "8080:8080"
    volumes:
      - pulsardata:/pulsar/data
      - pulsarconf:/pulsar/conf
    command: bin/pulsar standalone

volumes:
  pulsardata:
  pulsarconf:
